// Tests for TmbReader (beads-2mw.2). Fixtures under cpp/tests/fixtures/ are
// generated by Python's write_tmb() (see scratchpad gen_fixtures.py / the
// original src/tmb_format.py) so these tests verify byte-exact compatibility
// with the Python reference implementation.

#include "TmbReader.h"

#include <gtest/gtest.h>

#include <cstdlib>
#include <string>

namespace {

// Fixtures live next to this test's source; CMake/CTest's working directory
// isn't guaranteed, so resolve relative to a compile-time-known fixtures dir.
#ifndef TMB_TEST_FIXTURES_DIR
#define TMB_TEST_FIXTURES_DIR "cpp/tests/fixtures"
#endif

std::string FixturePath(const std::string& name) {
    return std::string(TMB_TEST_FIXTURES_DIR) + "/" + name;
}

} // namespace

TEST(TmbReader, RoundTripNormalFile) {
    injector_core::TmbReader reader(FixturePath("normal.tmb"));

    EXPECT_EQ(reader.vertexCount(), 12345);

    auto deltas = reader.deltas();
    ASSERT_EQ(deltas.size(), 4u);

    EXPECT_EQ(deltas[0].vertex_index, 0u);
    EXPECT_FLOAT_EQ(deltas[0].dx, 0.1f);
    EXPECT_FLOAT_EQ(deltas[0].dy, 0.2f);
    EXPECT_FLOAT_EQ(deltas[0].dz, 0.3f);

    EXPECT_EQ(deltas[1].vertex_index, 1u);
    EXPECT_FLOAT_EQ(deltas[1].dx, -0.5f);
    EXPECT_FLOAT_EQ(deltas[1].dy, 1.5f);
    EXPECT_FLOAT_EQ(deltas[1].dz, -2.5f);

    EXPECT_EQ(deltas[2].vertex_index, 99u);
    EXPECT_FLOAT_EQ(deltas[2].dx, 0.0f);
    EXPECT_FLOAT_EQ(deltas[2].dy, 0.0f);
    EXPECT_FLOAT_EQ(deltas[2].dz, 0.0f);

    EXPECT_EQ(deltas[3].vertex_index, 4294967295u);
    EXPECT_FLOAT_EQ(deltas[3].dx, 3.14159f);
    EXPECT_FLOAT_EQ(deltas[3].dy, -3.14159f);
    EXPECT_FLOAT_EQ(deltas[3].dz, 1.0f);
}

TEST(TmbReader, NegativeOneVertexCountRoundTrips) {
    // Regression case: vertex_count == -1 is a documented DSON sentinel for
    // "unspecified/same as base mesh". An earlier uint32_t packing silently
    // dropped every affected file -- vertex_count must stay signed.
    injector_core::TmbReader reader(FixturePath("negative_one_vertex_count.tmb"));

    EXPECT_EQ(reader.vertexCount(), -1);

    auto deltas = reader.deltas();
    ASSERT_EQ(deltas.size(), 2u);

    EXPECT_EQ(deltas[0].vertex_index, 0u);
    EXPECT_FLOAT_EQ(deltas[0].dx, 1.0f);
    EXPECT_FLOAT_EQ(deltas[0].dy, 2.0f);
    EXPECT_FLOAT_EQ(deltas[0].dz, 3.0f);

    EXPECT_EQ(deltas[1].vertex_index, 5u);
    EXPECT_FLOAT_EQ(deltas[1].dx, -1.0f);
    EXPECT_FLOAT_EQ(deltas[1].dy, -2.0f);
    EXPECT_FLOAT_EQ(deltas[1].dz, -3.0f);
}

TEST(TmbReader, EmptyDeltasFile) {
    injector_core::TmbReader reader(FixturePath("empty.tmb"));
    EXPECT_EQ(reader.vertexCount(), 0);
    EXPECT_EQ(reader.deltas().size(), 0u);
}

TEST(TmbReader, BadMagicThrowsInsteadOfCrashing) {
    // Reuse the normal fixture's path but point at a corrupted copy written
    // fresh into a temp file so we don't depend on fixture mutation.
    std::string path = FixturePath("bad_magic.tmb");
    {
        FILE* f = std::fopen(path.c_str(), "wb");
        ASSERT_NE(f, nullptr);
        const char bytes[16] = {'B', 'A', 'D', '!', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        std::fwrite(bytes, 1, sizeof(bytes), f);
        std::fclose(f);
    }

    EXPECT_THROW(injector_core::TmbReader reader(path), injector_core::TmbFormatError);

    std::remove(path.c_str());
}

TEST(TmbReader, TruncatedHeaderThrows) {
    std::string path = FixturePath("truncated_header.tmb");
    {
        FILE* f = std::fopen(path.c_str(), "wb");
        ASSERT_NE(f, nullptr);
        const char bytes[8] = {'T', 'M', 'B', '1', 0, 0, 0, 0};
        std::fwrite(bytes, 1, sizeof(bytes), f);
        std::fclose(f);
    }

    EXPECT_THROW(injector_core::TmbReader reader(path), injector_core::TmbFormatError);

    std::remove(path.c_str());
}

TEST(TmbReader, TruncatedDataSectionThrows) {
    std::string path = FixturePath("truncated_data.tmb");
    {
        FILE* f = std::fopen(path.c_str(), "wb");
        ASSERT_NE(f, nullptr);
        // Header claims 2 deltas but only provides bytes for a partial one.
        const unsigned char header[16] = {
            'T', 'M', 'B', '1',
            0x39, 0x30, 0x00, 0x00, // vertex_count = 12345 (LE int32)
            0x02, 0x00, 0x00, 0x00, // delta_count = 2
            0, 0, 0, 0              // reserved
        };
        std::fwrite(header, 1, sizeof(header), f);
        const unsigned char partial_delta[10] = {0};
        std::fwrite(partial_delta, 1, sizeof(partial_delta), f);
        std::fclose(f);
    }

    EXPECT_THROW(injector_core::TmbReader reader(path), injector_core::TmbFormatError);

    std::remove(path.c_str());
}
