from typing import Any, Protocol


class ChromaCollectionProtocol(Protocol):
    def count(self) -> int: ...


class ChromaDbManagerProtocol(Protocol):
    collection: ChromaCollectionProtocol

    def search(self, **kwargs: Any) -> dict: ...

    def get_db_stats(self) -> dict | None: ...


class SQLiteDbProtocol(Protocol):
    def count(self) -> int: ...

    def get_products(
        self,
        page: int = 1,
        page_size: int = 25,
        category: str | None = None,
        artist: str | None = None,
        compatible_figure: str | None = None,
        sort_by: str = "name",
        sort_dir: str = "asc",
    ) -> dict: ...

    def get_sku_row(self, sku: str) -> dict | None: ...

    def get_filter_values(self) -> dict: ...


class DazPgAnalyzerProtocol(Protocol):
    def count_skus(self) -> int: ...

    def get_content_roots(self) -> list[str]: ...

    def get_asset_files_by_sku(self, sku: str) -> list[dict] | None: ...


class DazScriptServerProtocol(Protocol):
    def status(self) -> dict: ...

    def is_available(self) -> bool: ...

    def browse_to_product(self, product_name: str) -> dict: ...

    def load_asset(self, asset_path: str) -> dict: ...

    def get_content_directories(self, force: bool = False) -> list[str]: ...


class UpdateTaskServiceProtocol(Protocol):
    def get_current(self) -> dict: ...

    def get_task(self, task_id: str) -> dict | None: ...

    def is_running(self) -> bool: ...

    def prune_old(self) -> None: ...

    def create_task(self, task_id: str) -> dict: ...

    def finish_from_task_entry(self, task_entry: dict) -> None: ...
